/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.BuyItem;
import org.openapitools.client.model.SellItem;
import org.openapitools.client.model.UpdateModuleSettingRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ModulesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ModulesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ModulesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getModuleSettings
     * @param token The bot token (required)
     * @param module The module name (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The module settings </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot or module not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getModuleSettingsCall(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bot/{token}/modules/{module}/settings"
            .replace("{" + "token" + "}", localVarApiClient.escapeString(token.toString()))
            .replace("{" + "module" + "}", localVarApiClient.escapeString(module.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getModuleSettingsValidateBeforeCall(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling getModuleSettings(Async)");
        }

        // verify the required parameter 'module' is set
        if (module == null) {
            throw new ApiException("Missing the required parameter 'module' when calling getModuleSettings(Async)");
        }

        return getModuleSettingsCall(token, module, _callback);

    }

    /**
     * Get Module Settings
     * Retrieve the settings of a specific module for a bot.
     * @param token The bot token (required)
     * @param module The module name (required)
     * @return Map&lt;String, String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The module settings </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot or module not found </td><td>  -  </td></tr>
     </table>
     */
    public Map<String, String> getModuleSettings(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module) throws ApiException {
        ApiResponse<Map<String, String>> localVarResp = getModuleSettingsWithHttpInfo(token, module);
        return localVarResp.getData();
    }

    /**
     * Get Module Settings
     * Retrieve the settings of a specific module for a bot.
     * @param token The bot token (required)
     * @param module The module name (required)
     * @return ApiResponse&lt;Map&lt;String, String&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The module settings </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot or module not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Map<String, String>> getModuleSettingsWithHttpInfo(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module) throws ApiException {
        okhttp3.Call localVarCall = getModuleSettingsValidateBeforeCall(token, module, null);
        Type localVarReturnType = new TypeToken<Map<String, String>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Module Settings (asynchronously)
     * Retrieve the settings of a specific module for a bot.
     * @param token The bot token (required)
     * @param module The module name (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The module settings </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot or module not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getModuleSettingsAsync(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module, final ApiCallback<Map<String, String>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getModuleSettingsValidateBeforeCall(token, module, _callback);
        Type localVarReturnType = new TypeToken<Map<String, String>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPublicBuyItems
     * @param token The bot token (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of buy items </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicBuyItemsCall(@javax.annotation.Nonnull String token, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bot/{token}/modules/buy/items"
            .replace("{" + "token" + "}", localVarApiClient.escapeString(token.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPublicBuyItemsValidateBeforeCall(@javax.annotation.Nonnull String token, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling getPublicBuyItems(Async)");
        }

        return getPublicBuyItemsCall(token, _callback);

    }

    /**
     * Get Buy Items
     * Retrieve a list of all buy items for the bot shop module.
     * @param token The bot token (required)
     * @return List&lt;BuyItem&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of buy items </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public List<BuyItem> getPublicBuyItems(@javax.annotation.Nonnull String token) throws ApiException {
        ApiResponse<List<BuyItem>> localVarResp = getPublicBuyItemsWithHttpInfo(token);
        return localVarResp.getData();
    }

    /**
     * Get Buy Items
     * Retrieve a list of all buy items for the bot shop module.
     * @param token The bot token (required)
     * @return ApiResponse&lt;List&lt;BuyItem&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of buy items </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<BuyItem>> getPublicBuyItemsWithHttpInfo(@javax.annotation.Nonnull String token) throws ApiException {
        okhttp3.Call localVarCall = getPublicBuyItemsValidateBeforeCall(token, null);
        Type localVarReturnType = new TypeToken<List<BuyItem>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Buy Items (asynchronously)
     * Retrieve a list of all buy items for the bot shop module.
     * @param token The bot token (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of buy items </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicBuyItemsAsync(@javax.annotation.Nonnull String token, final ApiCallback<List<BuyItem>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPublicBuyItemsValidateBeforeCall(token, _callback);
        Type localVarReturnType = new TypeToken<List<BuyItem>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPublicSellItems
     * @param token The bot token (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of sell items </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicSellItemsCall(@javax.annotation.Nonnull String token, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bot/{token}/modules/sell/items"
            .replace("{" + "token" + "}", localVarApiClient.escapeString(token.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPublicSellItemsValidateBeforeCall(@javax.annotation.Nonnull String token, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling getPublicSellItems(Async)");
        }

        return getPublicSellItemsCall(token, _callback);

    }

    /**
     * Get Sell Items
     * Retrieve a list of all sell items for the bot shop module.
     * @param token The bot token (required)
     * @return List&lt;SellItem&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of sell items </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public List<SellItem> getPublicSellItems(@javax.annotation.Nonnull String token) throws ApiException {
        ApiResponse<List<SellItem>> localVarResp = getPublicSellItemsWithHttpInfo(token);
        return localVarResp.getData();
    }

    /**
     * Get Sell Items
     * Retrieve a list of all sell items for the bot shop module.
     * @param token The bot token (required)
     * @return ApiResponse&lt;List&lt;SellItem&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of sell items </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<SellItem>> getPublicSellItemsWithHttpInfo(@javax.annotation.Nonnull String token) throws ApiException {
        okhttp3.Call localVarCall = getPublicSellItemsValidateBeforeCall(token, null);
        Type localVarReturnType = new TypeToken<List<SellItem>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Sell Items (asynchronously)
     * Retrieve a list of all sell items for the bot shop module.
     * @param token The bot token (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of sell items </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicSellItemsAsync(@javax.annotation.Nonnull String token, final ApiCallback<List<SellItem>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPublicSellItemsValidateBeforeCall(token, _callback);
        Type localVarReturnType = new TypeToken<List<SellItem>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateModuleSetting
     * @param token The bot token (required)
     * @param module The module name (required)
     * @param setting The setting to update (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Settings updated successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot or module not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateModuleSettingCall(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module, @javax.annotation.Nonnull UpdateModuleSettingRequest setting, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = setting;

        // create path and map variables
        String localVarPath = "/bot/{token}/modules/{module}/settings"
            .replace("{" + "token" + "}", localVarApiClient.escapeString(token.toString()))
            .replace("{" + "module" + "}", localVarApiClient.escapeString(module.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateModuleSettingValidateBeforeCall(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module, @javax.annotation.Nonnull UpdateModuleSettingRequest setting, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling updateModuleSetting(Async)");
        }

        // verify the required parameter 'module' is set
        if (module == null) {
            throw new ApiException("Missing the required parameter 'module' when calling updateModuleSetting(Async)");
        }

        // verify the required parameter 'setting' is set
        if (setting == null) {
            throw new ApiException("Missing the required parameter 'setting' when calling updateModuleSetting(Async)");
        }

        return updateModuleSettingCall(token, module, setting, _callback);

    }

    /**
     * Update Module Setting
     * Update a specific setting of a specific module for a bot.
     * @param token The bot token (required)
     * @param module The module name (required)
     * @param setting The setting to update (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Settings updated successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot or module not found </td><td>  -  </td></tr>
     </table>
     */
    public void updateModuleSetting(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module, @javax.annotation.Nonnull UpdateModuleSettingRequest setting) throws ApiException {
        updateModuleSettingWithHttpInfo(token, module, setting);
    }

    /**
     * Update Module Setting
     * Update a specific setting of a specific module for a bot.
     * @param token The bot token (required)
     * @param module The module name (required)
     * @param setting The setting to update (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Settings updated successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot or module not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> updateModuleSettingWithHttpInfo(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module, @javax.annotation.Nonnull UpdateModuleSettingRequest setting) throws ApiException {
        okhttp3.Call localVarCall = updateModuleSettingValidateBeforeCall(token, module, setting, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Update Module Setting (asynchronously)
     * Update a specific setting of a specific module for a bot.
     * @param token The bot token (required)
     * @param module The module name (required)
     * @param setting The setting to update (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Settings updated successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot or module not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateModuleSettingAsync(@javax.annotation.Nonnull String token, @javax.annotation.Nonnull String module, @javax.annotation.Nonnull UpdateModuleSettingRequest setting, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateModuleSettingValidateBeforeCall(token, module, setting, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
