/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.Module;
import org.openapitools.client.model.PublicBot;
import org.openapitools.client.model.Server;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PublicApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PublicApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PublicApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getPublicBot
     * @param token The bot token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The bot information </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicBotCall(@javax.annotation.Nullable String token, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bot/public";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPublicBotValidateBeforeCall(@javax.annotation.Nullable String token, final ApiCallback _callback) throws ApiException {
        return getPublicBotCall(token, _callback);

    }

    /**
     * Get Public Bot
     * Retrieve information about a public bot.
     * @param token The bot token (optional)
     * @return PublicBot
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The bot information </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public PublicBot getPublicBot(@javax.annotation.Nullable String token) throws ApiException {
        ApiResponse<PublicBot> localVarResp = getPublicBotWithHttpInfo(token);
        return localVarResp.getData();
    }

    /**
     * Get Public Bot
     * Retrieve information about a public bot.
     * @param token The bot token (optional)
     * @return ApiResponse&lt;PublicBot&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The bot information </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PublicBot> getPublicBotWithHttpInfo(@javax.annotation.Nullable String token) throws ApiException {
        okhttp3.Call localVarCall = getPublicBotValidateBeforeCall(token, null);
        Type localVarReturnType = new TypeToken<PublicBot>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Public Bot (asynchronously)
     * Retrieve information about a public bot.
     * @param token The bot token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The bot information </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicBotAsync(@javax.annotation.Nullable String token, final ApiCallback<PublicBot> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPublicBotValidateBeforeCall(token, _callback);
        Type localVarReturnType = new TypeToken<PublicBot>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPublicBotByLink
     * @param linkName The bot link name (required)
     * @param server The server where the bot connects to (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The bot information </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicBotByLinkCall(@javax.annotation.Nonnull String linkName, @javax.annotation.Nonnull String server, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bot/public/{linkName}"
            .replace("{" + "linkName" + "}", localVarApiClient.escapeString(linkName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (server != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("server", server));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPublicBotByLinkValidateBeforeCall(@javax.annotation.Nonnull String linkName, @javax.annotation.Nonnull String server, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'linkName' is set
        if (linkName == null) {
            throw new ApiException("Missing the required parameter 'linkName' when calling getPublicBotByLink(Async)");
        }

        // verify the required parameter 'server' is set
        if (server == null) {
            throw new ApiException("Missing the required parameter 'server' when calling getPublicBotByLink(Async)");
        }

        return getPublicBotByLinkCall(linkName, server, _callback);

    }

    /**
     * Get Public Bot by Link Name
     * Retrieve information about a public bot using its link name.
     * @param linkName The bot link name (required)
     * @param server The server where the bot connects to (required)
     * @return PublicBot
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The bot information </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public PublicBot getPublicBotByLink(@javax.annotation.Nonnull String linkName, @javax.annotation.Nonnull String server) throws ApiException {
        ApiResponse<PublicBot> localVarResp = getPublicBotByLinkWithHttpInfo(linkName, server);
        return localVarResp.getData();
    }

    /**
     * Get Public Bot by Link Name
     * Retrieve information about a public bot using its link name.
     * @param linkName The bot link name (required)
     * @param server The server where the bot connects to (required)
     * @return ApiResponse&lt;PublicBot&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The bot information </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PublicBot> getPublicBotByLinkWithHttpInfo(@javax.annotation.Nonnull String linkName, @javax.annotation.Nonnull String server) throws ApiException {
        okhttp3.Call localVarCall = getPublicBotByLinkValidateBeforeCall(linkName, server, null);
        Type localVarReturnType = new TypeToken<PublicBot>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Public Bot by Link Name (asynchronously)
     * Retrieve information about a public bot using its link name.
     * @param linkName The bot link name (required)
     * @param server The server where the bot connects to (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The bot information </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Bot not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicBotByLinkAsync(@javax.annotation.Nonnull String linkName, @javax.annotation.Nonnull String server, final ApiCallback<PublicBot> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPublicBotByLinkValidateBeforeCall(linkName, server, _callback);
        Type localVarReturnType = new TypeToken<PublicBot>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPublicModules
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of public modules </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicModulesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/modules";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPublicModulesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getPublicModulesCall(_callback);

    }

    /**
     * Get Public Modules
     * Retrieve a list of all public modules.
     * @return List&lt;Module&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of public modules </td><td>  -  </td></tr>
     </table>
     */
    public List<Module> getPublicModules() throws ApiException {
        ApiResponse<List<Module>> localVarResp = getPublicModulesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get Public Modules
     * Retrieve a list of all public modules.
     * @return ApiResponse&lt;List&lt;Module&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of public modules </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Module>> getPublicModulesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getPublicModulesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<Module>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Public Modules (asynchronously)
     * Retrieve a list of all public modules.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of public modules </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicModulesAsync(final ApiCallback<List<Module>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPublicModulesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<Module>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPublicServers
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of public servers </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicServersCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/servers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPublicServersValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getPublicServersCall(_callback);

    }

    /**
     * Get Public Servers
     * Retrieve a list of all public servers.
     * @return List&lt;Server&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of public servers </td><td>  -  </td></tr>
     </table>
     */
    public List<Server> getPublicServers() throws ApiException {
        ApiResponse<List<Server>> localVarResp = getPublicServersWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get Public Servers
     * Retrieve a list of all public servers.
     * @return ApiResponse&lt;List&lt;Server&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of public servers </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Server>> getPublicServersWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getPublicServersValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<Server>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Public Servers (asynchronously)
     * Retrieve a list of all public servers.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of public servers </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPublicServersAsync(final ApiCallback<List<Server>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPublicServersValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<Server>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
