/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * A detailed representation of a bot
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-24T14:59:48.257041210Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Bot {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  @javax.annotation.Nonnull
  private String token;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public static final String SERIALIZED_NAME_ONLINE = "online";
  @SerializedName(SERIALIZED_NAME_ONLINE)
  @javax.annotation.Nonnull
  private Boolean online = false;

  public static final String SERIALIZED_NAME_OWNER_ID = "ownerId";
  @SerializedName(SERIALIZED_NAME_OWNER_ID)
  @javax.annotation.Nonnull
  private Long ownerId;

  public static final String SERIALIZED_NAME_LAST_UPDATED = "lastUpdated";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
  @javax.annotation.Nonnull
  private OffsetDateTime lastUpdated;

  public static final String SERIALIZED_NAME_LINK_NAME = "linkName";
  @SerializedName(SERIALIZED_NAME_LINK_NAME)
  @javax.annotation.Nonnull
  private String linkName = "unknown";

  public static final String SERIALIZED_NAME_LAST_LINK = "lastLink";
  @SerializedName(SERIALIZED_NAME_LAST_LINK)
  @javax.annotation.Nonnull
  private OffsetDateTime lastLink;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_DISCORD = "discord";
  @SerializedName(SERIALIZED_NAME_DISCORD)
  @javax.annotation.Nullable
  private String discord;

  public Bot() {
  }

  public Bot id(@javax.annotation.Nonnull Long id) {
    this.id = id;
    return this;
  }

  /**
   * The numeric identifier of the bot
   * @return id
   */
  @javax.annotation.Nonnull
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull Long id) {
    this.id = id;
  }


  public Bot token(@javax.annotation.Nonnull String token) {
    this.token = token;
    return this;
  }

  /**
   * The main bot identifier
   * @return token
   */
  @javax.annotation.Nonnull
  public String getToken() {
    return token;
  }

  public void setToken(@javax.annotation.Nonnull String token) {
    this.token = token;
  }


  public Bot status(@javax.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * What the bot is currently doing
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
  }


  public Bot online(@javax.annotation.Nonnull Boolean online) {
    this.online = online;
    return this;
  }

  /**
   * Whether the bot is online or offline
   * @return online
   */
  @javax.annotation.Nonnull
  public Boolean getOnline() {
    return online;
  }

  public void setOnline(@javax.annotation.Nonnull Boolean online) {
    this.online = online;
  }


  public Bot ownerId(@javax.annotation.Nonnull Long ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * The user ID of the bot owner
   * @return ownerId
   */
  @javax.annotation.Nonnull
  public Long getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(@javax.annotation.Nonnull Long ownerId) {
    this.ownerId = ownerId;
  }


  public Bot lastUpdated(@javax.annotation.Nonnull OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

  /**
   * The date and time when the bot was last updated
   * @return lastUpdated
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(@javax.annotation.Nonnull OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  public Bot linkName(@javax.annotation.Nonnull String linkName) {
    this.linkName = linkName;
    return this;
  }

  /**
   * The bot&#39;s link name
   * @return linkName
   */
  @javax.annotation.Nonnull
  public String getLinkName() {
    return linkName;
  }

  public void setLinkName(@javax.annotation.Nonnull String linkName) {
    this.linkName = linkName;
  }


  public Bot lastLink(@javax.annotation.Nonnull OffsetDateTime lastLink) {
    this.lastLink = lastLink;
    return this;
  }

  /**
   * The date and time when the bot was last linked
   * @return lastLink
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getLastLink() {
    return lastLink;
  }

  public void setLastLink(@javax.annotation.Nonnull OffsetDateTime lastLink) {
    this.lastLink = lastLink;
  }


  public Bot description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * The bot&#39;s description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public Bot discord(@javax.annotation.Nullable String discord) {
    this.discord = discord;
    return this;
  }

  /**
   * The bot&#39;s Discord Server ID
   * @return discord
   */
  @javax.annotation.Nullable
  public String getDiscord() {
    return discord;
  }

  public void setDiscord(@javax.annotation.Nullable String discord) {
    this.discord = discord;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bot bot = (Bot) o;
    return Objects.equals(this.id, bot.id) &&
        Objects.equals(this.token, bot.token) &&
        Objects.equals(this.status, bot.status) &&
        Objects.equals(this.online, bot.online) &&
        Objects.equals(this.ownerId, bot.ownerId) &&
        Objects.equals(this.lastUpdated, bot.lastUpdated) &&
        Objects.equals(this.linkName, bot.linkName) &&
        Objects.equals(this.lastLink, bot.lastLink) &&
        Objects.equals(this.description, bot.description) &&
        Objects.equals(this.discord, bot.discord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, token, status, online, ownerId, lastUpdated, linkName, lastLink, description, discord);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bot {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    linkName: ").append(toIndentedString(linkName)).append("\n");
    sb.append("    lastLink: ").append(toIndentedString(lastLink)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    discord: ").append(toIndentedString(discord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "token", "status", "online", "ownerId", "lastUpdated", "linkName", "lastLink", "description", "discord"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "token", "status", "online", "ownerId", "lastUpdated", "linkName", "lastLink"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Bot
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Bot.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Bot is not found in the empty JSON string", Bot.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Bot.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Bot` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Bot.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (!jsonObj.get("linkName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `linkName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("linkName").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("discord") != null && !jsonObj.get("discord").isJsonNull()) && !jsonObj.get("discord").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `discord` to be a primitive type in the JSON string but got `%s`", jsonObj.get("discord").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Bot.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Bot' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Bot> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Bot.class));

       return (TypeAdapter<T>) new TypeAdapter<Bot>() {
           @Override
           public void write(JsonWriter out, Bot value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Bot read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Bot given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Bot
   * @throws IOException if the JSON string is invalid with respect to Bot
   */
  public static Bot fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Bot.class);
  }

  /**
   * Convert an instance of Bot to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

