/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BlockPosition;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * An item that can be bought in the bot shop
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-24T14:59:48.257041210Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class BuyItem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_NBT = "nbt";
  @SerializedName(SERIALIZED_NAME_NBT)
  @javax.annotation.Nullable
  private String nbt;

  public static final String SERIALIZED_NAME_ITEM_TYPE = "itemType";
  @SerializedName(SERIALIZED_NAME_ITEM_TYPE)
  @javax.annotation.Nonnull
  private String itemType;

  public static final String SERIALIZED_NAME_CHEST_POSITION = "chestPosition";
  @SerializedName(SERIALIZED_NAME_CHEST_POSITION)
  @javax.annotation.Nonnull
  private BlockPosition chestPosition;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private Float price;

  public BuyItem() {
  }

  public BuyItem id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * A 28-character case-sensitive alphanumeric identifier
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public BuyItem name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the item
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public BuyItem nbt(@javax.annotation.Nullable String nbt) {
    this.nbt = nbt;
    return this;
  }

  /**
   * The NBT data of the item in JSON format
   * @return nbt
   */
  @javax.annotation.Nullable
  public String getNbt() {
    return nbt;
  }

  public void setNbt(@javax.annotation.Nullable String nbt) {
    this.nbt = nbt;
  }


  public BuyItem itemType(@javax.annotation.Nonnull String itemType) {
    this.itemType = itemType;
    return this;
  }

  /**
   * The Minecraft ID of the item (e.g., \&quot;diamond_sword\&quot;)
   * @return itemType
   */
  @javax.annotation.Nonnull
  public String getItemType() {
    return itemType;
  }

  public void setItemType(@javax.annotation.Nonnull String itemType) {
    this.itemType = itemType;
  }


  public BuyItem chestPosition(@javax.annotation.Nonnull BlockPosition chestPosition) {
    this.chestPosition = chestPosition;
    return this;
  }

  /**
   * Get chestPosition
   * @return chestPosition
   */
  @javax.annotation.Nonnull
  public BlockPosition getChestPosition() {
    return chestPosition;
  }

  public void setChestPosition(@javax.annotation.Nonnull BlockPosition chestPosition) {
    this.chestPosition = chestPosition;
  }


  public BuyItem price(@javax.annotation.Nullable Float price) {
    this.price = price;
    return this;
  }

  /**
   * The price per sold item
   * @return price
   */
  @javax.annotation.Nullable
  public Float getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable Float price) {
    this.price = price;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyItem buyItem = (BuyItem) o;
    return Objects.equals(this.id, buyItem.id) &&
        Objects.equals(this.name, buyItem.name) &&
        Objects.equals(this.nbt, buyItem.nbt) &&
        Objects.equals(this.itemType, buyItem.itemType) &&
        Objects.equals(this.chestPosition, buyItem.chestPosition) &&
        Objects.equals(this.price, buyItem.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, nbt, itemType, chestPosition, price);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nbt: ").append(toIndentedString(nbt)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    chestPosition: ").append(toIndentedString(chestPosition)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "nbt", "itemType", "chestPosition", "price"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "itemType", "chestPosition"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BuyItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BuyItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in BuyItem is not found in the empty JSON string", BuyItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BuyItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BuyItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BuyItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("nbt") != null && !jsonObj.get("nbt").isJsonNull()) && !jsonObj.get("nbt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `nbt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nbt").toString()));
      }
      if (!jsonObj.get("itemType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `itemType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("itemType").toString()));
      }
      // validate the required field `chestPosition`
      BlockPosition.validateJsonElement(jsonObj.get("chestPosition"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BuyItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BuyItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BuyItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BuyItem.class));

       return (TypeAdapter<T>) new TypeAdapter<BuyItem>() {
           @Override
           public void write(JsonWriter out, BuyItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BuyItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BuyItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BuyItem
   * @throws IOException if the JSON string is invalid with respect to BuyItem
   */
  public static BuyItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BuyItem.class);
  }

  /**
   * Convert an instance of BuyItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

