/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * A grouped aggregation (e.g. by month) with a count
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-24T14:59:48.257041210Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class StatisticsGroup {
  public static final String SERIALIZED_NAME_TIME_GROUP = "time_group";
  @SerializedName(SERIALIZED_NAME_TIME_GROUP)
  @javax.annotation.Nullable
  private String timeGroup;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  @javax.annotation.Nullable
  private Long count;

  public StatisticsGroup() {
  }

  public StatisticsGroup timeGroup(@javax.annotation.Nullable String timeGroup) {
    this.timeGroup = timeGroup;
    return this;
  }

  /**
   * Time group label (e.g. \&quot;2025-08\&quot;)
   * @return timeGroup
   */
  @javax.annotation.Nullable
  public String getTimeGroup() {
    return timeGroup;
  }

  public void setTimeGroup(@javax.annotation.Nullable String timeGroup) {
    this.timeGroup = timeGroup;
  }


  public StatisticsGroup count(@javax.annotation.Nullable Long count) {
    this.count = count;
    return this;
  }

  /**
   * Number of events in this group
   * @return count
   */
  @javax.annotation.Nullable
  public Long getCount() {
    return count;
  }

  public void setCount(@javax.annotation.Nullable Long count) {
    this.count = count;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticsGroup statisticsGroup = (StatisticsGroup) o;
    return Objects.equals(this.timeGroup, statisticsGroup.timeGroup) &&
        Objects.equals(this.count, statisticsGroup.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeGroup, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticsGroup {\n");
    sb.append("    timeGroup: ").append(toIndentedString(timeGroup)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("time_group", "count"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatisticsGroup
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatisticsGroup.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in StatisticsGroup is not found in the empty JSON string", StatisticsGroup.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatisticsGroup.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatisticsGroup` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("time_group") != null && !jsonObj.get("time_group").isJsonNull()) && !jsonObj.get("time_group").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `time_group` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time_group").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatisticsGroup.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatisticsGroup' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatisticsGroup> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatisticsGroup.class));

       return (TypeAdapter<T>) new TypeAdapter<StatisticsGroup>() {
           @Override
           public void write(JsonWriter out, StatisticsGroup value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatisticsGroup read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatisticsGroup given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatisticsGroup
   * @throws IOException if the JSON string is invalid with respect to StatisticsGroup
   */
  public static StatisticsGroup fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatisticsGroup.class);
  }

  /**
   * Convert an instance of StatisticsGroup to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

