/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.StatisticsQueryFiltersMetadataInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * StatisticsQueryFilters
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-24T14:59:48.257041210Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class StatisticsQueryFilters {
  public static final String SERIALIZED_NAME_EVENT_TYPE = "eventType";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  @javax.annotation.Nullable
  private String eventType;

  public static final String SERIALIZED_NAME_BOT_ID = "botId";
  @SerializedName(SERIALIZED_NAME_BOT_ID)
  @javax.annotation.Nullable
  private String botId;

  public static final String SERIALIZED_NAME_SUB_PLAYER_UUID = "subPlayerUuid";
  @SerializedName(SERIALIZED_NAME_SUB_PLAYER_UUID)
  @javax.annotation.Nullable
  private String subPlayerUuid;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private List<StatisticsQueryFiltersMetadataInner> metadata = new ArrayList<>();

  public StatisticsQueryFilters() {
  }

  public StatisticsQueryFilters eventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * The type of event to filter by
   * @return eventType
   */
  @javax.annotation.Nullable
  public String getEventType() {
    return eventType;
  }

  public void setEventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }


  public StatisticsQueryFilters botId(@javax.annotation.Nullable String botId) {
    this.botId = botId;
    return this;
  }

  /**
   * The bot ID to filter by
   * @return botId
   */
  @javax.annotation.Nullable
  public String getBotId() {
    return botId;
  }

  public void setBotId(@javax.annotation.Nullable String botId) {
    this.botId = botId;
  }


  public StatisticsQueryFilters subPlayerUuid(@javax.annotation.Nullable String subPlayerUuid) {
    this.subPlayerUuid = subPlayerUuid;
    return this;
  }

  /**
   * The sub-player UUID to filter by
   * @return subPlayerUuid
   */
  @javax.annotation.Nullable
  public String getSubPlayerUuid() {
    return subPlayerUuid;
  }

  public void setSubPlayerUuid(@javax.annotation.Nullable String subPlayerUuid) {
    this.subPlayerUuid = subPlayerUuid;
  }


  public StatisticsQueryFilters metadata(@javax.annotation.Nullable List<StatisticsQueryFiltersMetadataInner> metadata) {
    this.metadata = metadata;
    return this;
  }

  public StatisticsQueryFilters addMetadataItem(StatisticsQueryFiltersMetadataInner metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * Metadata filters
   * @return metadata
   */
  @javax.annotation.Nullable
  public List<StatisticsQueryFiltersMetadataInner> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable List<StatisticsQueryFiltersMetadataInner> metadata) {
    this.metadata = metadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticsQueryFilters statisticsQueryFilters = (StatisticsQueryFilters) o;
    return Objects.equals(this.eventType, statisticsQueryFilters.eventType) &&
        Objects.equals(this.botId, statisticsQueryFilters.botId) &&
        Objects.equals(this.subPlayerUuid, statisticsQueryFilters.subPlayerUuid) &&
        Objects.equals(this.metadata, statisticsQueryFilters.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventType, botId, subPlayerUuid, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticsQueryFilters {\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    botId: ").append(toIndentedString(botId)).append("\n");
    sb.append("    subPlayerUuid: ").append(toIndentedString(subPlayerUuid)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("eventType", "botId", "subPlayerUuid", "metadata"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatisticsQueryFilters
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatisticsQueryFilters.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in StatisticsQueryFilters is not found in the empty JSON string", StatisticsQueryFilters.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatisticsQueryFilters.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatisticsQueryFilters` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("eventType") != null && !jsonObj.get("eventType").isJsonNull()) && !jsonObj.get("eventType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `eventType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eventType").toString()));
      }
      if ((jsonObj.get("botId") != null && !jsonObj.get("botId").isJsonNull()) && !jsonObj.get("botId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `botId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("botId").toString()));
      }
      if ((jsonObj.get("subPlayerUuid") != null && !jsonObj.get("subPlayerUuid").isJsonNull()) && !jsonObj.get("subPlayerUuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `subPlayerUuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subPlayerUuid").toString()));
      }
      if (jsonObj.get("metadata") != null && !jsonObj.get("metadata").isJsonNull()) {
        JsonArray jsonArraymetadata = jsonObj.getAsJsonArray("metadata");
        if (jsonArraymetadata != null) {
          // ensure the json data is an array
          if (!jsonObj.get("metadata").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `metadata` to be an array in the JSON string but got `%s`", jsonObj.get("metadata").toString()));
          }

          // validate the optional field `metadata` (array)
          for (int i = 0; i < jsonArraymetadata.size(); i++) {
            StatisticsQueryFiltersMetadataInner.validateJsonElement(jsonArraymetadata.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatisticsQueryFilters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatisticsQueryFilters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatisticsQueryFilters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatisticsQueryFilters.class));

       return (TypeAdapter<T>) new TypeAdapter<StatisticsQueryFilters>() {
           @Override
           public void write(JsonWriter out, StatisticsQueryFilters value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatisticsQueryFilters read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatisticsQueryFilters given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatisticsQueryFilters
   * @throws IOException if the JSON string is invalid with respect to StatisticsQueryFilters
   */
  public static StatisticsQueryFilters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatisticsQueryFilters.class);
  }

  /**
   * Convert an instance of StatisticsQueryFilters to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

