/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.StatisticsEventMetadata;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * A single event returned in statistics results
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-24T14:59:48.257041210Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class StatisticsEvent {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_EVENT_TYPE = "event_type";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  @javax.annotation.Nullable
  private String eventType;

  public static final String SERIALIZED_NAME_OCCURRED_AT = "occurred_at";
  @SerializedName(SERIALIZED_NAME_OCCURRED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime occurredAt;

  public static final String SERIALIZED_NAME_BOT_ID = "bot_id";
  @SerializedName(SERIALIZED_NAME_BOT_ID)
  @javax.annotation.Nullable
  private String botId;

  public static final String SERIALIZED_NAME_SUB_PLAYER_UUID = "sub_player_uuid";
  @SerializedName(SERIALIZED_NAME_SUB_PLAYER_UUID)
  @javax.annotation.Nullable
  private String subPlayerUuid;

  public static final String SERIALIZED_NAME_SUB_PLAYER_NAME = "sub_player_name";
  @SerializedName(SERIALIZED_NAME_SUB_PLAYER_NAME)
  @javax.annotation.Nullable
  private String subPlayerName;

  public static final String SERIALIZED_NAME_HAS_SUB_USER = "has_sub_user";
  @SerializedName(SERIALIZED_NAME_HAS_SUB_USER)
  @javax.annotation.Nullable
  private Integer hasSubUser;

  public static final String SERIALIZED_NAME_MODULE_ID = "module_id";
  @SerializedName(SERIALIZED_NAME_MODULE_ID)
  @javax.annotation.Nullable
  private String moduleId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private List<StatisticsEventMetadata> metadata = new ArrayList<>();

  public StatisticsEvent() {
  }

  public StatisticsEvent id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Numeric event identifier
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public StatisticsEvent eventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * The event type name
   * @return eventType
   */
  @javax.annotation.Nullable
  public String getEventType() {
    return eventType;
  }

  public void setEventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }


  public StatisticsEvent occurredAt(@javax.annotation.Nullable OffsetDateTime occurredAt) {
    this.occurredAt = occurredAt;
    return this;
  }

  /**
   * When the event occurred
   * @return occurredAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getOccurredAt() {
    return occurredAt;
  }

  public void setOccurredAt(@javax.annotation.Nullable OffsetDateTime occurredAt) {
    this.occurredAt = occurredAt;
  }


  public StatisticsEvent botId(@javax.annotation.Nullable String botId) {
    this.botId = botId;
    return this;
  }

  /**
   * Bot identifier (string)
   * @return botId
   */
  @javax.annotation.Nullable
  public String getBotId() {
    return botId;
  }

  public void setBotId(@javax.annotation.Nullable String botId) {
    this.botId = botId;
  }


  public StatisticsEvent subPlayerUuid(@javax.annotation.Nullable String subPlayerUuid) {
    this.subPlayerUuid = subPlayerUuid;
    return this;
  }

  /**
   * Sub-player UUID (may be null)
   * @return subPlayerUuid
   */
  @javax.annotation.Nullable
  public String getSubPlayerUuid() {
    return subPlayerUuid;
  }

  public void setSubPlayerUuid(@javax.annotation.Nullable String subPlayerUuid) {
    this.subPlayerUuid = subPlayerUuid;
  }


  public StatisticsEvent subPlayerName(@javax.annotation.Nullable String subPlayerName) {
    this.subPlayerName = subPlayerName;
    return this;
  }

  /**
   * Sub-player name (may be null)
   * @return subPlayerName
   */
  @javax.annotation.Nullable
  public String getSubPlayerName() {
    return subPlayerName;
  }

  public void setSubPlayerName(@javax.annotation.Nullable String subPlayerName) {
    this.subPlayerName = subPlayerName;
  }


  public StatisticsEvent hasSubUser(@javax.annotation.Nullable Integer hasSubUser) {
    this.hasSubUser = hasSubUser;
    return this;
  }

  /**
   * Flag indicating presence of a sub-user (0 or 1)
   * @return hasSubUser
   */
  @javax.annotation.Nullable
  public Integer getHasSubUser() {
    return hasSubUser;
  }

  public void setHasSubUser(@javax.annotation.Nullable Integer hasSubUser) {
    this.hasSubUser = hasSubUser;
  }


  public StatisticsEvent moduleId(@javax.annotation.Nullable String moduleId) {
    this.moduleId = moduleId;
    return this;
  }

  /**
   * Module identifier (may be null)
   * @return moduleId
   */
  @javax.annotation.Nullable
  public String getModuleId() {
    return moduleId;
  }

  public void setModuleId(@javax.annotation.Nullable String moduleId) {
    this.moduleId = moduleId;
  }


  public StatisticsEvent createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * When the event record was created
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public StatisticsEvent metadata(@javax.annotation.Nullable List<StatisticsEventMetadata> metadata) {
    this.metadata = metadata;
    return this;
  }

  public StatisticsEvent addMetadataItem(StatisticsEventMetadata metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * Additional key/value metadata for the event
   * @return metadata
   */
  @javax.annotation.Nullable
  public List<StatisticsEventMetadata> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable List<StatisticsEventMetadata> metadata) {
    this.metadata = metadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticsEvent statisticsEvent = (StatisticsEvent) o;
    return Objects.equals(this.id, statisticsEvent.id) &&
        Objects.equals(this.eventType, statisticsEvent.eventType) &&
        Objects.equals(this.occurredAt, statisticsEvent.occurredAt) &&
        Objects.equals(this.botId, statisticsEvent.botId) &&
        Objects.equals(this.subPlayerUuid, statisticsEvent.subPlayerUuid) &&
        Objects.equals(this.subPlayerName, statisticsEvent.subPlayerName) &&
        Objects.equals(this.hasSubUser, statisticsEvent.hasSubUser) &&
        Objects.equals(this.moduleId, statisticsEvent.moduleId) &&
        Objects.equals(this.createdAt, statisticsEvent.createdAt) &&
        Objects.equals(this.metadata, statisticsEvent.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, eventType, occurredAt, botId, subPlayerUuid, subPlayerName, hasSubUser, moduleId, createdAt, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticsEvent {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    occurredAt: ").append(toIndentedString(occurredAt)).append("\n");
    sb.append("    botId: ").append(toIndentedString(botId)).append("\n");
    sb.append("    subPlayerUuid: ").append(toIndentedString(subPlayerUuid)).append("\n");
    sb.append("    subPlayerName: ").append(toIndentedString(subPlayerName)).append("\n");
    sb.append("    hasSubUser: ").append(toIndentedString(hasSubUser)).append("\n");
    sb.append("    moduleId: ").append(toIndentedString(moduleId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "event_type", "occurred_at", "bot_id", "sub_player_uuid", "sub_player_name", "has_sub_user", "module_id", "created_at", "metadata"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatisticsEvent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatisticsEvent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in StatisticsEvent is not found in the empty JSON string", StatisticsEvent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatisticsEvent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatisticsEvent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("event_type") != null && !jsonObj.get("event_type").isJsonNull()) && !jsonObj.get("event_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `event_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_type").toString()));
      }
      if ((jsonObj.get("bot_id") != null && !jsonObj.get("bot_id").isJsonNull()) && !jsonObj.get("bot_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `bot_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bot_id").toString()));
      }
      if ((jsonObj.get("sub_player_uuid") != null && !jsonObj.get("sub_player_uuid").isJsonNull()) && !jsonObj.get("sub_player_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sub_player_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sub_player_uuid").toString()));
      }
      if ((jsonObj.get("sub_player_name") != null && !jsonObj.get("sub_player_name").isJsonNull()) && !jsonObj.get("sub_player_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sub_player_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sub_player_name").toString()));
      }
      if ((jsonObj.get("module_id") != null && !jsonObj.get("module_id").isJsonNull()) && !jsonObj.get("module_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `module_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("module_id").toString()));
      }
      if (jsonObj.get("metadata") != null && !jsonObj.get("metadata").isJsonNull()) {
        JsonArray jsonArraymetadata = jsonObj.getAsJsonArray("metadata");
        if (jsonArraymetadata != null) {
          // ensure the json data is an array
          if (!jsonObj.get("metadata").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `metadata` to be an array in the JSON string but got `%s`", jsonObj.get("metadata").toString()));
          }

          // validate the optional field `metadata` (array)
          for (int i = 0; i < jsonArraymetadata.size(); i++) {
            StatisticsEventMetadata.validateJsonElement(jsonArraymetadata.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatisticsEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatisticsEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatisticsEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatisticsEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<StatisticsEvent>() {
           @Override
           public void write(JsonWriter out, StatisticsEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatisticsEvent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatisticsEvent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatisticsEvent
   * @throws IOException if the JSON string is invalid with respect to StatisticsEvent
   */
  public static StatisticsEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatisticsEvent.class);
  }

  /**
   * Convert an instance of StatisticsEvent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

