/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.StatisticsQueryFilters;
import org.openapitools.client.model.StatisticsQuerySort;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * A query for bot statistics
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-24T14:59:48.257041210Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class StatisticsQuery {
  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  @javax.annotation.Nullable
  private StatisticsQueryFilters filters;

  public static final String SERIALIZED_NAME_SORT = "sort";
  @SerializedName(SERIALIZED_NAME_SORT)
  @javax.annotation.Nullable
  private StatisticsQuerySort sort;

  /**
   * Gets or Sets groupByTime
   */
  @JsonAdapter(GroupByTimeEnum.Adapter.class)
  public enum GroupByTimeEnum {
    MINUTE("minute"),
    
    HOUR("hour"),
    
    DAY("day"),
    
    WEEK("week"),
    
    MONTH("month"),
    
    YEAR("year");

    private String value;

    GroupByTimeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GroupByTimeEnum fromValue(String value) {
      for (GroupByTimeEnum b : GroupByTimeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<GroupByTimeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GroupByTimeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GroupByTimeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return GroupByTimeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      GroupByTimeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_GROUP_BY_TIME = "groupByTime";
  @SerializedName(SERIALIZED_NAME_GROUP_BY_TIME)
  @javax.annotation.Nullable
  private GroupByTimeEnum groupByTime;

  public static final String SERIALIZED_NAME_GROUP_BY_METADATA_KEY = "groupByMetadataKey";
  @SerializedName(SERIALIZED_NAME_GROUP_BY_METADATA_KEY)
  @javax.annotation.Nullable
  private String groupByMetadataKey;

  public static final String SERIALIZED_NAME_INCLUDE_METADATA = "includeMetadata";
  @SerializedName(SERIALIZED_NAME_INCLUDE_METADATA)
  @javax.annotation.Nullable
  private Boolean includeMetadata;

  public static final String SERIALIZED_NAME_METADATA_STATS = "metadataStats";
  @SerializedName(SERIALIZED_NAME_METADATA_STATS)
  @javax.annotation.Nullable
  private Boolean metadataStats;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  @javax.annotation.Nullable
  private Long limit;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  @javax.annotation.Nullable
  private Long offset;

  public StatisticsQuery() {
  }

  public StatisticsQuery filters(@javax.annotation.Nullable StatisticsQueryFilters filters) {
    this.filters = filters;
    return this;
  }

  /**
   * Get filters
   * @return filters
   */
  @javax.annotation.Nullable
  public StatisticsQueryFilters getFilters() {
    return filters;
  }

  public void setFilters(@javax.annotation.Nullable StatisticsQueryFilters filters) {
    this.filters = filters;
  }


  public StatisticsQuery sort(@javax.annotation.Nullable StatisticsQuerySort sort) {
    this.sort = sort;
    return this;
  }

  /**
   * Get sort
   * @return sort
   */
  @javax.annotation.Nullable
  public StatisticsQuerySort getSort() {
    return sort;
  }

  public void setSort(@javax.annotation.Nullable StatisticsQuerySort sort) {
    this.sort = sort;
  }


  public StatisticsQuery groupByTime(@javax.annotation.Nullable GroupByTimeEnum groupByTime) {
    this.groupByTime = groupByTime;
    return this;
  }

  /**
   * Get groupByTime
   * @return groupByTime
   */
  @javax.annotation.Nullable
  public GroupByTimeEnum getGroupByTime() {
    return groupByTime;
  }

  public void setGroupByTime(@javax.annotation.Nullable GroupByTimeEnum groupByTime) {
    this.groupByTime = groupByTime;
  }


  public StatisticsQuery groupByMetadataKey(@javax.annotation.Nullable String groupByMetadataKey) {
    this.groupByMetadataKey = groupByMetadataKey;
    return this;
  }

  /**
   * Get groupByMetadataKey
   * @return groupByMetadataKey
   */
  @javax.annotation.Nullable
  public String getGroupByMetadataKey() {
    return groupByMetadataKey;
  }

  public void setGroupByMetadataKey(@javax.annotation.Nullable String groupByMetadataKey) {
    this.groupByMetadataKey = groupByMetadataKey;
  }


  public StatisticsQuery includeMetadata(@javax.annotation.Nullable Boolean includeMetadata) {
    this.includeMetadata = includeMetadata;
    return this;
  }

  /**
   * Get includeMetadata
   * @return includeMetadata
   */
  @javax.annotation.Nullable
  public Boolean getIncludeMetadata() {
    return includeMetadata;
  }

  public void setIncludeMetadata(@javax.annotation.Nullable Boolean includeMetadata) {
    this.includeMetadata = includeMetadata;
  }


  public StatisticsQuery metadataStats(@javax.annotation.Nullable Boolean metadataStats) {
    this.metadataStats = metadataStats;
    return this;
  }

  /**
   * Get metadataStats
   * @return metadataStats
   */
  @javax.annotation.Nullable
  public Boolean getMetadataStats() {
    return metadataStats;
  }

  public void setMetadataStats(@javax.annotation.Nullable Boolean metadataStats) {
    this.metadataStats = metadataStats;
  }


  public StatisticsQuery limit(@javax.annotation.Nullable Long limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @javax.annotation.Nullable
  public Long getLimit() {
    return limit;
  }

  public void setLimit(@javax.annotation.Nullable Long limit) {
    this.limit = limit;
  }


  public StatisticsQuery offset(@javax.annotation.Nullable Long offset) {
    this.offset = offset;
    return this;
  }

  /**
   * Get offset
   * @return offset
   */
  @javax.annotation.Nullable
  public Long getOffset() {
    return offset;
  }

  public void setOffset(@javax.annotation.Nullable Long offset) {
    this.offset = offset;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticsQuery statisticsQuery = (StatisticsQuery) o;
    return Objects.equals(this.filters, statisticsQuery.filters) &&
        Objects.equals(this.sort, statisticsQuery.sort) &&
        Objects.equals(this.groupByTime, statisticsQuery.groupByTime) &&
        Objects.equals(this.groupByMetadataKey, statisticsQuery.groupByMetadataKey) &&
        Objects.equals(this.includeMetadata, statisticsQuery.includeMetadata) &&
        Objects.equals(this.metadataStats, statisticsQuery.metadataStats) &&
        Objects.equals(this.limit, statisticsQuery.limit) &&
        Objects.equals(this.offset, statisticsQuery.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filters, sort, groupByTime, groupByMetadataKey, includeMetadata, metadataStats, limit, offset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticsQuery {\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    groupByTime: ").append(toIndentedString(groupByTime)).append("\n");
    sb.append("    groupByMetadataKey: ").append(toIndentedString(groupByMetadataKey)).append("\n");
    sb.append("    includeMetadata: ").append(toIndentedString(includeMetadata)).append("\n");
    sb.append("    metadataStats: ").append(toIndentedString(metadataStats)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("filters", "sort", "groupByTime", "groupByMetadataKey", "includeMetadata", "metadataStats", "limit", "offset"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatisticsQuery
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatisticsQuery.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in StatisticsQuery is not found in the empty JSON string", StatisticsQuery.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatisticsQuery.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatisticsQuery` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `filters`
      if (jsonObj.get("filters") != null && !jsonObj.get("filters").isJsonNull()) {
        StatisticsQueryFilters.validateJsonElement(jsonObj.get("filters"));
      }
      // validate the optional field `sort`
      if (jsonObj.get("sort") != null && !jsonObj.get("sort").isJsonNull()) {
        StatisticsQuerySort.validateJsonElement(jsonObj.get("sort"));
      }
      if ((jsonObj.get("groupByTime") != null && !jsonObj.get("groupByTime").isJsonNull()) && !jsonObj.get("groupByTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `groupByTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("groupByTime").toString()));
      }
      // validate the optional field `groupByTime`
      if (jsonObj.get("groupByTime") != null && !jsonObj.get("groupByTime").isJsonNull()) {
        GroupByTimeEnum.validateJsonElement(jsonObj.get("groupByTime"));
      }
      if ((jsonObj.get("groupByMetadataKey") != null && !jsonObj.get("groupByMetadataKey").isJsonNull()) && !jsonObj.get("groupByMetadataKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `groupByMetadataKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("groupByMetadataKey").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatisticsQuery.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatisticsQuery' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatisticsQuery> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatisticsQuery.class));

       return (TypeAdapter<T>) new TypeAdapter<StatisticsQuery>() {
           @Override
           public void write(JsonWriter out, StatisticsQuery value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatisticsQuery read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatisticsQuery given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatisticsQuery
   * @throws IOException if the JSON string is invalid with respect to StatisticsQuery
   */
  public static StatisticsQuery fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatisticsQuery.class);
  }

  /**
   * Convert an instance of StatisticsQuery to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

