/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.StatisticsEvent;
import org.openapitools.client.model.StatisticsGroup;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * The result of a statistics query
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-24T14:59:48.257041210Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class StatisticsResult {
  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  @javax.annotation.Nullable
  private List<StatisticsEvent> events = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL_AVAILABLE = "totalAvailable";
  @SerializedName(SERIALIZED_NAME_TOTAL_AVAILABLE)
  @javax.annotation.Nullable
  private Long totalAvailable;

  public static final String SERIALIZED_NAME_GROUPED = "grouped";
  @SerializedName(SERIALIZED_NAME_GROUPED)
  @javax.annotation.Nullable
  private List<StatisticsGroup> grouped = new ArrayList<>();

  public static final String SERIALIZED_NAME_CACHE_HIT = "cache_hit";
  @SerializedName(SERIALIZED_NAME_CACHE_HIT)
  @javax.annotation.Nullable
  private Boolean cacheHit = false;

  public static final String SERIALIZED_NAME_INFLUX = "influx";
  @SerializedName(SERIALIZED_NAME_INFLUX)
  @javax.annotation.Nullable
  private String influx;

  public static final String SERIALIZED_NAME_EXT = "ext";
  @SerializedName(SERIALIZED_NAME_EXT)
  @javax.annotation.Nullable
  private String ext;

  public static final String SERIALIZED_NAME_EXEC_TIME = "execTime";
  @SerializedName(SERIALIZED_NAME_EXEC_TIME)
  @javax.annotation.Nullable
  private Float execTime;

  public StatisticsResult() {
  }

  public StatisticsResult events(@javax.annotation.Nullable List<StatisticsEvent> events) {
    this.events = events;
    return this;
  }

  public StatisticsResult addEventsItem(StatisticsEvent eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * A list of events returned by the query
   * @return events
   */
  @javax.annotation.Nullable
  public List<StatisticsEvent> getEvents() {
    return events;
  }

  public void setEvents(@javax.annotation.Nullable List<StatisticsEvent> events) {
    this.events = events;
  }


  public StatisticsResult totalAvailable(@javax.annotation.Nullable Long totalAvailable) {
    this.totalAvailable = totalAvailable;
    return this;
  }

  /**
   * Total number of available events for the query (pagination or sth...)
   * @return totalAvailable
   */
  @javax.annotation.Nullable
  public Long getTotalAvailable() {
    return totalAvailable;
  }

  public void setTotalAvailable(@javax.annotation.Nullable Long totalAvailable) {
    this.totalAvailable = totalAvailable;
  }


  public StatisticsResult grouped(@javax.annotation.Nullable List<StatisticsGroup> grouped) {
    this.grouped = grouped;
    return this;
  }

  public StatisticsResult addGroupedItem(StatisticsGroup groupedItem) {
    if (this.grouped == null) {
      this.grouped = new ArrayList<>();
    }
    this.grouped.add(groupedItem);
    return this;
  }

  /**
   * Aggregated counts grouped by time or other keys
   * @return grouped
   */
  @javax.annotation.Nullable
  public List<StatisticsGroup> getGrouped() {
    return grouped;
  }

  public void setGrouped(@javax.annotation.Nullable List<StatisticsGroup> grouped) {
    this.grouped = grouped;
  }


  public StatisticsResult cacheHit(@javax.annotation.Nullable Boolean cacheHit) {
    this.cacheHit = cacheHit;
    return this;
  }

  /**
   * Whether the response was served from cache
   * @return cacheHit
   */
  @javax.annotation.Nullable
  public Boolean getCacheHit() {
    return cacheHit;
  }

  public void setCacheHit(@javax.annotation.Nullable Boolean cacheHit) {
    this.cacheHit = cacheHit;
  }


  public StatisticsResult influx(@javax.annotation.Nullable String influx) {
    this.influx = influx;
    return this;
  }

  /**
   * Influx query status (e.g. \&quot;partial\&quot;, \&quot;full\&quot;)
   * @return influx
   */
  @javax.annotation.Nullable
  public String getInflux() {
    return influx;
  }

  public void setInflux(@javax.annotation.Nullable String influx) {
    this.influx = influx;
  }


  public StatisticsResult ext(@javax.annotation.Nullable String ext) {
    this.ext = ext;
    return this;
  }

  /**
   * External query status (e.g. \&quot;partial\&quot;, \&quot;full\&quot;)
   * @return ext
   */
  @javax.annotation.Nullable
  public String getExt() {
    return ext;
  }

  public void setExt(@javax.annotation.Nullable String ext) {
    this.ext = ext;
  }


  public StatisticsResult execTime(@javax.annotation.Nullable Float execTime) {
    this.execTime = execTime;
    return this;
  }

  /**
   * Execution time in milliseconds
   * @return execTime
   */
  @javax.annotation.Nullable
  public Float getExecTime() {
    return execTime;
  }

  public void setExecTime(@javax.annotation.Nullable Float execTime) {
    this.execTime = execTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticsResult statisticsResult = (StatisticsResult) o;
    return Objects.equals(this.events, statisticsResult.events) &&
        Objects.equals(this.totalAvailable, statisticsResult.totalAvailable) &&
        Objects.equals(this.grouped, statisticsResult.grouped) &&
        Objects.equals(this.cacheHit, statisticsResult.cacheHit) &&
        Objects.equals(this.influx, statisticsResult.influx) &&
        Objects.equals(this.ext, statisticsResult.ext) &&
        Objects.equals(this.execTime, statisticsResult.execTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(events, totalAvailable, grouped, cacheHit, influx, ext, execTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticsResult {\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    totalAvailable: ").append(toIndentedString(totalAvailable)).append("\n");
    sb.append("    grouped: ").append(toIndentedString(grouped)).append("\n");
    sb.append("    cacheHit: ").append(toIndentedString(cacheHit)).append("\n");
    sb.append("    influx: ").append(toIndentedString(influx)).append("\n");
    sb.append("    ext: ").append(toIndentedString(ext)).append("\n");
    sb.append("    execTime: ").append(toIndentedString(execTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("events", "totalAvailable", "grouped", "cache_hit", "influx", "ext", "execTime"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatisticsResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatisticsResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in StatisticsResult is not found in the empty JSON string", StatisticsResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatisticsResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatisticsResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("events") != null && !jsonObj.get("events").isJsonNull()) {
        JsonArray jsonArrayevents = jsonObj.getAsJsonArray("events");
        if (jsonArrayevents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("events").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `events` to be an array in the JSON string but got `%s`", jsonObj.get("events").toString()));
          }

          // validate the optional field `events` (array)
          for (int i = 0; i < jsonArrayevents.size(); i++) {
            StatisticsEvent.validateJsonElement(jsonArrayevents.get(i));
          };
        }
      }
      if (jsonObj.get("grouped") != null && !jsonObj.get("grouped").isJsonNull()) {
        JsonArray jsonArraygrouped = jsonObj.getAsJsonArray("grouped");
        if (jsonArraygrouped != null) {
          // ensure the json data is an array
          if (!jsonObj.get("grouped").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `grouped` to be an array in the JSON string but got `%s`", jsonObj.get("grouped").toString()));
          }

          // validate the optional field `grouped` (array)
          for (int i = 0; i < jsonArraygrouped.size(); i++) {
            StatisticsGroup.validateJsonElement(jsonArraygrouped.get(i));
          };
        }
      }
      if ((jsonObj.get("influx") != null && !jsonObj.get("influx").isJsonNull()) && !jsonObj.get("influx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `influx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("influx").toString()));
      }
      if ((jsonObj.get("ext") != null && !jsonObj.get("ext").isJsonNull()) && !jsonObj.get("ext").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `ext` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ext").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatisticsResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatisticsResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatisticsResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatisticsResult.class));

       return (TypeAdapter<T>) new TypeAdapter<StatisticsResult>() {
           @Override
           public void write(JsonWriter out, StatisticsResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatisticsResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatisticsResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatisticsResult
   * @throws IOException if the JSON string is invalid with respect to StatisticsResult
   */
  public static StatisticsResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatisticsResult.class);
  }

  /**
   * Convert an instance of StatisticsResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

