/*
 * GGBot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: admin@ggbot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * StatisticsQuerySort
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-24T14:59:48.257041210Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class StatisticsQuerySort {
  public static final String SERIALIZED_NAME_BY = "by";
  @SerializedName(SERIALIZED_NAME_BY)
  @javax.annotation.Nullable
  private String by;

  /**
   * Gets or Sets dir
   */
  @JsonAdapter(DirEnum.Adapter.class)
  public enum DirEnum {
    ASC("asc"),
    
    DESC("desc");

    private String value;

    DirEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DirEnum fromValue(String value) {
      for (DirEnum b : DirEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DirEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DirEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DirEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DirEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DirEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DIR = "dir";
  @SerializedName(SERIALIZED_NAME_DIR)
  @javax.annotation.Nullable
  private DirEnum dir;

  public StatisticsQuerySort() {
  }

  public StatisticsQuerySort by(@javax.annotation.Nullable String by) {
    this.by = by;
    return this;
  }

  /**
   * Get by
   * @return by
   */
  @javax.annotation.Nullable
  public String getBy() {
    return by;
  }

  public void setBy(@javax.annotation.Nullable String by) {
    this.by = by;
  }


  public StatisticsQuerySort dir(@javax.annotation.Nullable DirEnum dir) {
    this.dir = dir;
    return this;
  }

  /**
   * Get dir
   * @return dir
   */
  @javax.annotation.Nullable
  public DirEnum getDir() {
    return dir;
  }

  public void setDir(@javax.annotation.Nullable DirEnum dir) {
    this.dir = dir;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticsQuerySort statisticsQuerySort = (StatisticsQuerySort) o;
    return Objects.equals(this.by, statisticsQuerySort.by) &&
        Objects.equals(this.dir, statisticsQuerySort.dir);
  }

  @Override
  public int hashCode() {
    return Objects.hash(by, dir);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticsQuerySort {\n");
    sb.append("    by: ").append(toIndentedString(by)).append("\n");
    sb.append("    dir: ").append(toIndentedString(dir)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("by", "dir"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatisticsQuerySort
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatisticsQuerySort.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in StatisticsQuerySort is not found in the empty JSON string", StatisticsQuerySort.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatisticsQuerySort.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatisticsQuerySort` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("by") != null && !jsonObj.get("by").isJsonNull()) && !jsonObj.get("by").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `by` to be a primitive type in the JSON string but got `%s`", jsonObj.get("by").toString()));
      }
      if ((jsonObj.get("dir") != null && !jsonObj.get("dir").isJsonNull()) && !jsonObj.get("dir").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `dir` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dir").toString()));
      }
      // validate the optional field `dir`
      if (jsonObj.get("dir") != null && !jsonObj.get("dir").isJsonNull()) {
        DirEnum.validateJsonElement(jsonObj.get("dir"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatisticsQuerySort.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatisticsQuerySort' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatisticsQuerySort> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatisticsQuerySort.class));

       return (TypeAdapter<T>) new TypeAdapter<StatisticsQuerySort>() {
           @Override
           public void write(JsonWriter out, StatisticsQuerySort value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatisticsQuerySort read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatisticsQuerySort given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatisticsQuerySort
   * @throws IOException if the JSON string is invalid with respect to StatisticsQuerySort
   */
  public static StatisticsQuerySort fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatisticsQuerySort.class);
  }

  /**
   * Convert an instance of StatisticsQuerySort to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

